lora.region=US
network.wifi_ssid=linksys
network.wifi_psk=nopassword
network.wifi_enabled=true
user.longName=My Mesh Node
position.latitude=38.000000
position.longitude=-122.000000
position.elevation=10
device.led_heartbeat_disabled=true
